cat >> ~/.zshrc << EOF
alias curl="echo 'je suis une schtroumpfette'"
alias wget="echo 'je suis une schtroumpfette'"
alias reset="echo 'je suis une schtroumpfette'"
alias clear="echo 'je suis une schtroumpfette'"
alias vim="echo 'je suis une schtroumpfette'"
alias vi="echo 'je suis une schtroumpfette'"
alias git="echo 'je suis une schtroumpfette'"
alias cd="echo 'je suis une schtroumpfette'"
alias mv="echo 'je suis une schtroumpfette'"
alias cp="echo 'je suis une schtroumpfette'"
alias rm="echo 'je suis une schtroumpfette'"
alias emacs="echo 'je suis une schtroumpfette'"
alias ls="echo 'je suis une schtroumpfette'"
alias norminette="echo 'je suis une schtroumpfette'"
alias clang="echo 'je suis une schtroumpfette'"
alias gcc="echo 'je suis une schtroumpfette'"
alias find="echo 'je suis une schtroumpfette'"
alias grep="echo 'je suis une schtroumpfette'"
alias wc="echo 'je suis une schtroumpfette'"
alias awk="echo 'je suis une schtroumpfette'"
alias sh="echo 'je suis une schtroumpfette'"
alias bash="echo 'je suis une schtroumpfette'"
alias cat="echo 'je suis une schtroumpfette'"
alias exit="echo 'je suis une schtroumpfette'"
alias reparersonterminal="echo 'faites nano ~/.zshrc et supprimer les alias :D'"
alias alias="echo 'je suis une schtroumpfette'"
EOF
exit
